[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404

[dev]
  command = "npm run dev"
  port = 8080
